--- OneSmart 配置专用覆写 ---
[General]
DISABLEUDPQUIC = 1

# 自动下载 OneSmart 模板
DOWNLOAD_FILE = url=https://raw.githubusercontent.com/666OS/YYDS/main/mihomo/config/OneSmart.yaml, path=/etc/openclash/config/OneSmart.yaml, cron=0 6   *, force=false

# 设置默认配置文件
CONFIG_FILE = /etc/openclash/config/OneSmart.yaml

[Overwrite]

# 写入订阅 URL（由环境变量提供）
+proxy-providers:
  花云:
    url: "$ENKEY1"
  AZ:
    url: "$ENKEY2"

SUBINFOURL = $ENKEY1

# 统一追加 rule-providers
+rule-providers:
  PT:
    type: http
    behavior: domain
    format: mrs
    url: "https://github.com/666OS/rules/raw/release/mihomo/domain/Download.mrs"
    path: "./ruleprovider/PT.mrs"
    interval: 86400

  PT-D:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/fengwei0789/Rule/main/DST-PORT-direct.yaml"
    path: "./ruleprovider/PT-D.yaml"
    interval: 86400

# 统一追加 rules
+rules:
  - RULE-SET,PT,国内流量
  - RULE-SET,PT-D,国内流量
